// Code generated by "stringer -type=uponRule -trimprefix=upon"; DO NOT EDIT.

package qbft

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[uponUnknown-0]
	_ = x[uponValidPrePrepare-1]
	_ = x[uponQuorumPrepare-2]
	_ = x[uponQuorumCommit-3]
	_ = x[uponMinRoundChange-4]
	_ = x[uponQuorumRoundChange-5]
}

const _uponRule_name = "UnknownValidPrePrepareQuorumPrepareQuorumCommitMinRoundChangeQuorumRoundChange"

var _uponRule_index = [...]uint8{0, 7, 22, 35, 47, 61, 78}

func (i uponRule) String() string {
	if i < 0 || i >= uponRule(len(_uponRule_index)-1) {
		return "uponRule(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _uponRule_name[_uponRule_index[i]:_uponRule_index[i+1]]
}
